def getimages():
    return {
    "baby": "       _____",
    "burrito": "     '       '",
    "watching": "    / .6 6.   \\",
    "happy": "    /  ^ ^    \\",
    "staring": "    /  o o    \\",
    "sleep": "    /  - -    \\",
    "Zs": "    /  - -    \\  z  z  Z  Z",
    "hearing": "   (    ^     ,)",
    "listening": "   (    ^     ,)",
    "smiling": "    \\   __,   /",
    "wide": "    \\   O     /",
    "silence": "    \\   .     /",
    "sad": "    \\   n     /",
    "B": "     `._____.'",
    "b": "     /       \\",
    "still": "    /         \\",
    "wrapped": "   |           |",
    "bundled": "    \\         /",
    "very": "     \\       /",
    "tightly": "      -------",
    "now": "    /         \\",
    "spreading": "   (           )",
    "legs": "   /   /   \\   \\",
    "wiggling": "  /   /     \\   \\",
    "toes": " -----       -----"
}